// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxshvanljvdxahiextiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4c2h2YW5sanZkeGFoaWV4dGl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MTU0NjMsImV4cCI6MjA2NzM5MTQ2M30.m7dTjwcIC04xUOGNxh69JzX-ict6N-yGOX_a1mFbIvw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});